apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contacts-api
  template:
    metadata:
      labels:
        app: contacts-api
    spec:
      containers:
        - name: contacts-api
          image: ${ECR_REGISTRY}/contacts-api:latest
          ports:
            - containerPort: 5001
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5001"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: mongodb-uri
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
